# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '20230810-NirzarGandhi-NYCSchools' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'SDWebImage', '~> 5.16.0'

end
